### ISSUE TITLE
Securly Blocked It yesterday.

### ISSUE THREAD

**Issue by TonyKillam** [DogeNetwork/v4#10]
The site was working fine yesterday. Now Securly Is Detecting it as a "Anonymous Proxy"

**Comment by Gr4ys0n** [comment]
https://news.suncube.de/app

**Comment by DerpmanDev** [comment]
Please do not open an issue if your school/blocker has blocked the site. That is not our problem. You could try making your own links with the tutorials in our Discord or use our link bot.
