### ISSUE TITLE
YouTube not working

### ISSUE THREAD

**Issue by Garfeed33** [DogeNetwork/v4#103]
Every time I try to play a video on Youtube, it just doesn't play/load. Like, it just doesn't start. I'm signed in on a burner account and everything, but it just doesn't seem to play. I don't know if it's my school's wifi or not, but I've had this issue with pretty much every other proxy that I've tried to use? Can I get an explanation why it might not work because my puny brain can't even comprehend coding. (for reference, stuff like YouTube worked with github proxys at the end of the last school year, but now none of them do, often displaying something along the lines of "network error")

**Comment by tomochks2816** [comment]
Isn’t it because of YouTube’s bot prevention measures?

![image](https://github.com/user-attachments/assets/1cdeefd1-ca56-419f-b18e-8a8e9bc3087b)

**Comment by Garfeed33** [comment]
I thought I might be that, but I signed in using a Google account.

**Comment by DerpmanDev** [comment]
YouTube seems to have been blocking all datacenter IPs, we can't do anything about it.
However, you can use [Indivious](https://inv.tux.pizza/), which is just a YouTube frontend.
