### ISSUE TITLE
Shell Shockers not loading

### ISSUE THREAD

**Issue by sivsome** [DogeNetwork/v4#106]
I have tried countless proxies and this is the only one that will load, but it will give a matchmaker error. But still, any way to fix this?

**Comment by sivsome** [comment]
(i can't provide an image cause the site wont load on my main device as an extension is interfering with it)

**Comment by DerpmanDev** [comment]
Unfortunately, we cannot fix this problem as we are not the ones maintaining the proxy system. Instead, you can make a issue at the [Ultraviolet](https://github.com/titaniumnetwork-dev/Ultraviolet) GitHub.
