### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BaceSpaby** [DogeNetwork/v4#12]
Does this disable monitoring? I want to unblock websites but continue to allow teachers to monitor me so I don't get in trouble.

**Comment by BaceSpaby** [comment]
The monitoring in question is through the GoGuardian extension.

Also I noticed that you're on the Gimkit discord nice

**Comment by BaceSpaby** [comment]
Would there be a way to add more deployment options? all the websites so far have been blocked.

**Comment by DerpmanDev** [comment]
I cannot guarantee that your teacher will not be able to monitor you when you are using the proxy, but I we do have a feature where they cannot redirect you to another site with GoGuardian.

**Comment by Thrillerdome** [comment]
hey! I try to open reddit and it does, but it does not let me type anything, do you know why? (Btw you are actually my hero in ap human geography, just know you are appreciated) :)

**Comment by Thrillerdome** [comment]
Wait now I cant open it at all, it says "This site cant be reached" :(

**Comment by frantene** [comment]
I have something to say Doge...Discord doesn't work. It keeps saying "New login detected", when i verify it. It sorts of reloads server port. So now it says another new login. Same as for your games. they all reload after some time. Estimated about 2 minutes every time.

**Comment by DerpmanDev** [comment]
For the reloading, that may be because of your browser's built in Performance mode, that automatically puts tabs to sleep. For the login in Discord, that is a common issue, and I recommend enabling 2FA so that it won't ask you for email confirmation, it will only ask for a code.

**Comment by DerpmanDev** [comment]
I hope you find an solution to your problem. Closing this issue now.
