### ISSUE TITLE
After 2 sec youtube is dead

### ISSUE THREAD

**Issue by Infiell** [DogeNetwork/v4#131]
Video play any timing and quality 2-3 sec and stuck.
Network activity is 0
![image](https://github.com/user-attachments/assets/25b67d45-4508-4829-bfbf-a17eee53c574)
After refresh page network activity up and down again

**Comment by Infiell** [comment]
And this
![image](https://github.com/user-attachments/assets/ec7ce38f-d0e3-4cd2-9ca2-6b5d2c066ebf)

**Comment by BeezBumba** [comment]
youtube-nocookie.com simple. it has no cookie so it cant get blocked

**Comment by sysolace** [comment]
> I'd contact the developers of Ultraviolet, this isn't a Doge issue
