### ISSUE TITLE
Slow internet connection? Mine or doge

### ISSUE THREAD

**Issue by cosmicgalaxies3** [DogeNetwork/v4#138]
I don't know what's happening as when I try using websites (discord, magma.io, flockmod, etc.) Its always slow for some reason as it will literally look like and infinite loading/connecting screen. Please help! (I swear my wifi isn't like this 😔 )

**Comment by sysolace** [comment]
Clear cache

**Comment by cosmicgalaxies3** [comment]
And u tell me that when its blocked. At least I know, thanks
