### ISSUE TITLE
Special Key - Escape Key doesn't work. 

### ISSUE THREAD

**Issue by Msushil20** [DogeNetwork/v4#18]
The escape key used to work for this Doge proxy, but now it doesn't work for my site that I use. I use amazon luna, and now when I hit the escape key it skips using the key for the website and instead exits out of the full screened site itself. Here's a picture for what I'm talking about.

It says to restart my browser but that doesn't work either, same thing for my friend as well.

![Screenshot (4)](https://github.com/DogeNetwork/v4/assets/123318620/9b8b5869-e8be-4ef5-80d0-d1e93a26004c)

**Comment by DerpmanDev** [comment]
Does the website force you to enter full-screen to be able to play? If not, then that may be why the error is occurring. Maybe the website isn't supposed to be in full-screen (I'm not entirely sure, I don't use Amazon Luna)

**Comment by Msushil20** [comment]
> Does the website force you to enter full-screen to be able to play? If not, then that may be why the error is occurring. Maybe the website isn't supposed to be in full-screen (I'm not entirely sure, I don't use Amazon Luna)

Yes it does force me to enter full screen. The key used to work I think in you previous deployment of DOGE but it doesn’t work now. Do you know if it’s cuz of an update that you realized in this version?

**Comment by DerpmanDev** [comment]
I don't think so, I only updated the UI and not the code. Maybe try this:
Go to Doge Unblocker.
Press CTRL+Shift+I to enter inspect.
Click "Console."
Copy and paste this:
```location.href = '/service/' + Ultraviolet.codec.xor.encode('YOUR-WEBSITE-LINK');```

Replace "YOUR-WEBSITE-LINK" with the link of your site and include the `https://` in it.

**Comment by Msushil20** [comment]
> I don't think so, I only updated the UI and not the code. Maybe try this: Go to Doge Unblocker. Press CTRL+Shift+I to enter inspect. Click "Console." Copy and paste this: `location.href = '/service/' + Ultraviolet.codec.xor.encode('YOUR-WEBSITE-LINK');`
> 
> Replace "YOUR-WEBSITE-LINK" with the link of your site and include the `https://` in it.

I did it, check it is there on your end

**Comment by DerpmanDev** [comment]
Send me the site link then

**Comment by Msushil20** [comment]
> Send me the site link then

The link for the site is https://luna.amazon.com/detail/B0BTRVRN6M

**Comment by DerpmanDev** [comment]
I don't have Amazon Prime so I can't see what the error is

**Comment by Msushil20** [comment]
> I don't have Amazon Prime so I can't see what the error is

Its alright, I figured out a way to get past it, I connect my controller to it then I can use the in game esc settings. Thanks for your time to answer.

**Comment by DerpmanDev** [comment]
No problem, glad you got the issue resolved!
