### ISSUE TITLE
damn 20% chatgpt and still having bs

### ISSUE THREAD

**Issue by Wackolmao** [DogeNetwork/v4#2]
I set up everything correctly cloning then running npm i then npm start but still i cant access the application even though it says running on 8080 and when i deployed it in vercel it also keeps changing ip address [not the domain] is that smth vercel does or issit smth in ur code

**Comment by DerpmanDev** [comment]
its your problem, not vercel's. when you clone it on vercel, don't put any npm or stuff like that, i already set it up with vercel.json. just clone, and deploy.

**Comment by Wackolmao** [comment]
how is it my probelm i just clone it on vercel but when i try accessing discord [like login] it says verify ip which i do but then it keeps saying to verify and then in my email inbox which i use for discord the ip verifiaction message keeps changing

**Comment by Wackolmao** [comment]
also can u like leave a guide on how to set it up like locally and link it to a domain or smth?

**Comment by DerpmanDev** [comment]
> how is it my probelm i just clone it on vercel but when i try accessing discord [like login] it says verify ip which i do but then it keeps saying to verify and then in my email inbox which i use for discord the ip verifiaction message keeps changing

Can you be specific and describe your issue further? I'm not really sure what you are trying to say. Are you getting an error from deploying or from using Discord?

For further support, please join our [Discord](https://discord.gg/ffDf3Nq9mK) so I can help you better that way.

**Comment by Wackolmao** [comment]
so when u login to discord with ur acc on a new device with new ip it asks u to check ur email for verification but then after completing it keeps asking and when i check my email it says a different ip but all is where the unblocker is hosted in

**Comment by DerpmanDev** [comment]
make sure you put the verification link in the proxy as well. make sure you're using the same proxy link too. also discord has been having some issues on uv based proxies anyway so that may be why you're getting that issue

**Comment by Wackolmao** [comment]
well thing is i used dogeunblocker v1 yes i am old and it worked but not v4? and can u reopen v1 and v2?

**Comment by DerpmanDev** [comment]
We cannot open V1 or V2 because it has been deleted.

Join the [Discord](https://discord.gg/ffDf3Nq9mK) for further questions or help.

**Comment by mecharis-420** [comment]
Guy's discord isnt working and add roblox
