### ISSUE TITLE
Vercel requires payment

### ISSUE THREAD

**Issue by Gl1tchblade** [DogeNetwork/v4#21]
Vercel now wants payment from me anyway to bypass this?

**Comment by Msushil20** [comment]
To bypass that I just created my own proxy, same doge but my own domain n stuff, Join the discord and follow the deploy to vercel instructions

**Comment by Gl1tchblade** [comment]
Tutorial doesn't mention anything

**Comment by DerpmanDev** [comment]
It may have been because you exceeded their usage limit on the free plan. Try creating a new account.

**Comment by DerpmanDev** [comment]
Hope you resolved your issue, closing this now.
