### ISSUE TITLE
Can this item be accessed by a specified URL? For example, if I want to access youtube.com, my website is a.com. When accessing the browser, enter a.com/xxxx/youtube.com to access which of the following?

### ISSUE THREAD

**Issue by itq5** [DogeNetwork/v4#24]
Can this item be accessed by a specified URL? For example, if I want to access youtube.com, my website is a.com. When accessing the browser, enter a.com/xxxx/youtube.com to access which of the following?

**Comment by DerpmanDev** [comment]
idk what you're saying. i kind of have an idea, though.
our url is encoded, so it would be `a.com/service/encoded-url-for-https://youtube.com`
to encode the url, go into our site, click into inspect and into console, and type 'Ultraviolet.codec.xor.encode('https://your-website.com');' to find the encoded version of it

**Comment by DerpmanDev** [comment]
Hope you resolved your issue/question. Closing this issue now.
