### ISSUE TITLE
It is not easy to open a new website after opening a website. It is recommended to set a top address bar, in which you can enter a new address to jump and refresh.

### ISSUE THREAD

**Issue by itq5** [DogeNetwork/v4#26]
It is not easy to open a new website after opening a website. It is recommended to set a top address bar, in which you can enter a new address to jump and refresh.

**Comment by DerpmanDev** [comment]
Again, please do not open issues if you do not have an actual problem. You can tell us your suggestions in our [Discord.](https://discord.gg/unblocking)

Our site is a normal proxy site, not a tabbed proxy site. If our service does not fit your needs, you are welcome to use another proxy site that supports tabs.
