### ISSUE TITLE
Is this a website or something else?

### ISSUE THREAD

**Issue by Esfirr** [DogeNetwork/v4#3]
Basically, how would one be able to use this?

**Comment by DerpmanDev** [comment]
its a site unblocker website. you can deploy it using the links i provided in readme.md (on the bottom of it) OR, you can join our discord and run /getlink, which will give you a link.

**Comment by Esfirr** [comment]
The link in the read me has expired :o

**Comment by DerpmanDev** [comment]
> The link in the read me has expired :o

do you mean our discord? you can join [here](https://discord.gg/rJyGZ6RRy6)
