### ISSUE TITLE
CrazyGames game crashes on login button press;

### ISSUE THREAD

**Issue by KDust7** [DogeNetwork/v4#30]
On visiting CrazyGames.com via proxy and play the Kirka.io game, you are unable to login through any platform. The button is clickable, it opens up a new tab, but crashes and becomes unresponsive.
Video: 

https://github.com/DogeNetwork/v4/assets/146490067/93a8c9f6-6b91-44d4-9226-f465536bbb18

sorry the video quality is bad lmao 
obs decided to be messed up today and i really didn't want to redo it
so there

**Comment by KDust7** [comment]
sorry i didn't add label as bug, but its a bug

**Comment by fomer3996** [comment]
why not just go to kirka.io instead of crazygames?

**Comment by KDust7** [comment]
kirka.io produces the same thing;
its just kirka.io crashes/hangs the page, crazy games is at least playable as guest

**Comment by DerpmanDev** [comment]
The proxy does not support every site. Some parts of the page can be broken. This can be caused by the site having a VPN/Proxy detection system. As far as I know, there has not been a solution to this.

**Comment by DerpmanDev** [comment]
This cannot be fixed, Ultraviolet does not support this.
