### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by XxSoggyPancakesxX** [DogeNetwork/v4#36]
So, Discord will not load, it stays on the looping logo page where you first open discord, I've waited 5-10 mins

It may be on my end, it happens after I log in.

**Comment by DerpmanDev** [comment]
It is not on your end. This is because we have exceeded the bandwidth limit on our hosting, which causes the slow site. It's also because of our backend. I have resolved the issue.

**Comment by XxSoggyPancakesxX** [comment]
Sorry to bother, but it's still happening, I'm positive it's on my side.
