### ISSUE TITLE
Problem with deployment to github pages.

### ISSUE THREAD

**Issue by ii0k** [DogeNetwork/v4#42]
Since the websites it has links to deploy to are blocked for me, I want to deploy it to github pages. When I do, however, it leads to the README file. Is this just me being stupid? (For more context i tried deploying with main/root and main/docs, and neither of them worked.)

Here are some screenshots -

![Screenshot 2024-02-20 8 42 08 AM](https://github.com/DogeNetwork/v4/assets/125227374/731c9d30-1107-44b7-a12e-71732d677dbb)
![Screenshot 2024-02-20 8 42 42 AM](https://github.com/DogeNetwork/v4/assets/125227374/f4200ef2-2561-425c-a217-2e1f3aa4c566)

**Comment by MlgRaying** [comment]
You can't deploy this to github pages, you have do it somewhere else.

**Comment by KDust7** [comment]
github pages is a static service- 
doge requires a backend which means this wouldn't work
if you want a service in github that works with doge, consider codespaces
there's a tutorial on the discord

**Comment by WaveDemure** [comment]
you can't deploy to github pages even if it was static (external bare) it wouldn't work that well gh pages due to some issues

**Comment by DerpmanDev** [comment]
There's your answer. Closing this issue now
