### ISSUE TITLE
Render Deployments Don't Work

### ISSUE THREAD

**Issue by deploymentsdontban** [DogeNetwork/v4#43]
says invalid repo, then i went back to this repo and tried to click the button again if it changed. still no worky

**Comment by KDust7** [comment]
doge v4 repo is blacklisted. 

follow the tutorial in the discord server for the new way

**Comment by WaveDemure** [comment]
use dns deploy or make a docker image of the site and deploy it on render there

**Comment by DerpmanDev** [comment]
Please join our Discord for more tutorials on deployments, and a possible fix for Render. Closing this issue now.
