### ISSUE TITLE
Help hosting on other platforms that Vercel.app

### ISSUE THREAD

**Issue by QuietNStealthy** [DogeNetwork/v4#45]
Please allow me to understand by commenting if you can help in anyway whatsoever!

**Comment by KDust7** [comment]
title is not so clear.
please elaborate

**Comment by DerpmanDev** [comment]
If you are looking for other platforms to deploy Doge, you can join our [Discord](https://discord.gg/unblocking) for methods

**Comment by DerpmanDev** [comment]
Hope your issue was resolved, closing this issue now.
