### ISSUE TITLE
Surfdoge.pro is blocked

### ISSUE THREAD

**Issue by breadcrumbsgames** [DogeNetwork/v4#51]
Surfdoge.pro is blocked. Can you please deploy a working GitHub Pages version? Thanks.

**Comment by funkymokey** [comment]
Deploy your own using Vercel

**Comment by DerpmanDev** [comment]
You can join our Discord for more links, or you can make your own through our deployment tutorials, also located in our Discord.

https://discord,gg/unblocking

**Comment by 1coolmatt8083** [comment]
i could help make a list of deploy ments that i deployed

**Comment by yet66** [comment]
> Surfdoge.pro is blocked. Can you please deploy a working GitHub Pages version? Thanks.

Deploying doge to GitHub pages is not possible

**Comment by 1coolmatt8083** [comment]
ya i will work on it

**Comment by breadcrumbsgames** [comment]
> Deploy your own using Vercel

I did and it worked, thanks!
