### ISSUE TITLE
Goguardian

### ISSUE THREAD

**Issue by NATHANIM2012** [DogeNetwork/v4#54]
My school blocks it repetitively exactly when I make one! I am very mad. Is there anything you can do?

**Comment by DerpmanDev** [comment]
Not that I know of, unfortunately. Try to keep the links to yourself, and don't share them with others. Have you tried looking at [this tutorial](https://www.youtube.com/watch?v=kBTGO672UJ4) instead?

**Comment by KDust7** [comment]
Make sure you are using DNS Deploy. If you are, try finding a domain that is public, but has a less hosts used number
This increases the chance of you making an unblocked link. Most schools, if there is no web page at a domain (which most FreeDNS domains are), block the domain immediately, so do NOT visit the original domain before hand to check if it is blocked. I have personal experience from this lmao

**Comment by 1coolmatt8083** [comment]
do u guys have any unblockers that work to play roblox

**Comment by 1coolmatt8083** [comment]
csause my school uses lightspeed and im trying to find a unblocked that will work with the now.gg site and it doesn't show the proxy/vpn popup

**Comment by CelloKit** [comment]
please don't use the issues tab to ask for links
anyways to fix this proxy detection popup, just refresh repeatedly
I don't know the exact steps though. There is a entry in the bypasses channel that says new Roblox bypass
use this to bypass the proxy/VPN popup

**Comment by 1coolmatt8083** [comment]
". There is a entry in the bypasses channel that says new Roblox bypass
use this to bypass the proxy/VPN popup"
-what do u mean by this can u show me?? thx

**Comment by KDust7** [comment]
The bypasses channel is in the discord, available at https://discord.gg/unblocking
Join it, and you'll see what I mean

**Comment by gdg-network** [comment]
Use vercel. Vercel is unblocked for goguardian
