### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by bloodymayhem** [DogeNetwork/v4#57]
I don't think that is a big issue but can someone tell me why does it show "404 error" when I click some game/app. It's very annoying and confusing:(

**Comment by 1coolmatt8083** [comment]
oh and by the way im using ca.indiancoins.com

**Comment by DerpmanDev** [comment]
Please do not share the links you get from the Discord Link Bot. @1coolmatt8083 

The 404 issue likely means that the UV service worker was not registered.

**Comment by 1coolmatt8083** [comment]
ummm what???

**Comment by 1coolmatt8083** [comment]
what does that mean!!!??
