### ISSUE TITLE
GeForce now

### ISSUE THREAD

**Issue by ajjhboys** [DogeNetwork/v4#60]
it keeps saying xml error

**Comment by 1coolmatt8083** [comment]
i hope they fix that i may be able to help though

**Comment by 1coolmatt8083** [comment]
go into apps and push google

**Comment by 1coolmatt8083** [comment]
ya so instead of using the url search bar on the tital page(which doesent work)
i just use the google app (wich is in apps ) and that works for me (sometimes) just keep reloading and it will work aventarly

**Comment by 1coolmatt8083** [comment]
can any one shar some of the updated doge links for me on this thread that would be help full since I cant get on the discord thx :)

**Comment by ieatkidsforbreakfest** [comment]
@ajjhboys you lil kid alr so this is how it works so first take off about blank this is crucial step then log into gforce normally after u do this u should get the xml error close that tab and the other tab but dont close the gforce tab the the error tabs now after u do this press the refresh button where the tab is not the refresh button on doge unblocker dont press that one press the one on top then after u do that it should open the error tab again after it does that just go back to the original gforce tab the first one u opened and u should be logged in if u need more help ill send screen shots or a video on how to do it step by step just add me on discord user:azgamer653

**Comment by ieatkidsforbreakfest** [comment]
@CelloKit you lil kid alr so this is how it works so first take off about blank if u dont know how go to setting then go to advance cloaking then turn it off now do this BC its crucial step. now then log into gforce normally and after u do this u should get the xml error close that tab and the other tab but dont close the gforce tab the the error tabs ONLY now after u do this press the refresh button not the refresh button on doge unblocker dont press that one press the one on top then after u do that it should open the error tab again after it does that just go back to the original gforce tab the first one u opened and u should be logged in if u need more help ill send screen shots or a video on how to do it step by step just add me on discord user:azgamer653

**Comment by DerpmanDev** [comment]
This issue has been fixed.
