### ISSUE TITLE
roblox not working

### ISSUE THREAD

**Issue by speedcomic** [DogeNetwork/v4#62]
when i open roblox it just brings me to doge unbllocker like this
![Screenshot 2024-04-29 1 22 52 PM](https://github.com/DogeNetwork/v4/assets/168462125/e40b18da-da51-462a-adbc-ef8d786bc259)

**Comment by DerpmanDev** [comment]
Yes, because the Roblox link you are using is outdated, please join our [Discord](https://discord.gg/unblocking) for updated links.
<br>
> Reminder: Do not share your links!

**Comment by 1coolmatt8083** [comment]
can u shar some of the updated links on this thread cause I cant get on discord right now and it would be easer thx,: )
