### ISSUE TITLE
Range Error

### ISSUE THREAD

**Issue by RickAstley-1** [DogeNetwork/v4#66]
When i try to open anything in the doge unblocked it says "RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599]." i don't know why this is happening but nothing will work

**Comment by DerpmanDev** [comment]
That was an issue with our links, it should work now.
<br>
> Reminder: Do not share your links!

**Comment by 1coolmatt8083** [comment]
can u put some links on this thread because i cant opan discord right now, thx
