### ISSUE TITLE
crazy games don't work

### ISSUE THREAD

**Issue by peaceunblockker** [DogeNetwork/v4#67]
some games in crazy games don't work like buildnowgg

**Comment by 1coolmatt8083** [comment]
hey

**Comment by 1coolmatt8083** [comment]
do u have a updated doge link u can shar with me

**Comment by 1coolmatt8083** [comment]
(because some one made a mistake were instead of loading they crash each time)

**Comment by 1coolmatt8083** [comment]
but ya if u can shar me a updatsed link of doge that u use or from the discord

**Comment by peaceunblockker** [comment]
wethebestmusic.vercel.app

**Comment by DerpmanDev** [comment]
@1coolmatt8083 @peaceunblockker Sharing links from our Discord Link Bot is strictly prohibited. Do not ask for links here.

As for the CrazyGames issue, that cannot be fixed at this time.

**Comment by 1coolmatt8083** [comment]
so i figured out the issue

**Comment by 1coolmatt8083** [comment]
the links that u are using are not the ones u forked soo u may need to fork and run your OWN links
