### ISSUE TITLE
Vercel Deployment

### ISSUE THREAD

**Issue by Proxieru** [DogeNetwork/v4#69]
Hello,
When clicking the button to deploy to vercel and then clicking create deployment, it says there was an unexpected error while cloning the repo. Is this just on my end?

Also, I tried deploying a vercel deployment with the url [https://github.com/DogeNetwork/v4.git] when you try to enter a website it gives you a range error exactly like issue #68.

**Comment by 1coolmatt8083** [comment]
you have to fork your own copy of it

**Comment by 1coolmatt8083** [comment]
heres the steps
1) press fork and accept your own copy
2)go to vercel
3)press new project
4) search your project
5) Deploy And ENJOY!!!!

**Comment by Proxieru** [comment]
Hello,
It's been awhile since i've written this issue and i'm glad I came back to it
thanks for helping me with my issue, I will try it now!
