### ISSUE TITLE
Doge links being blocked when opened

### ISSUE THREAD

**Issue by Ny4zU** [DogeNetwork/v4#70]
Hi Hi, so the doge links I get from the discord server are being blocked on my school laptop and I was wondering why it is happening, I have never shared my links with anyone nor showed anyone the discord so I am very confused as to why It is happening. I was also wondering if you can deploy the unblocker page inside of a github codespace? If it is possible could I get a tutorial or step by step on how to do so?

**Comment by 1coolmatt8083** [comment]
which links are u using

**Comment by 1coolmatt8083** [comment]
make of the links that are blocked for u and I can make a new deployment of them

**Comment by 1coolmatt8083** [comment]
oh and try using this-[]( https://interstellar-gold-kappa.vercel.app/1)
but if u give me the blocked doge links I can make "copies of them"

**Comment by Ny4zU** [comment]
> make of the links that are blocked for u and I can make a new deployment of them



> oh and try using this- but if u give me the blocked doge links I can make "copies of them"

 https://the.doge.hardchromesolution.com/apps

**Comment by 1coolmatt8083** [comment]
ok thx hang tight this might take a few minutes

**Comment by 1coolmatt8083** [comment]
acualy dont use that link i will get u another one try these
-https://doge-network-neon.vercel.app/
-https://ca.indiancoins.com/
-https://v4-orpin-seven.vercel.app/

**Comment by 1coolmatt8083** [comment]
also send me some more of the blocked discord links or any of the links that people send
(I want to see what the problem might be)

**Comment by DerpmanDev** [comment]
@1coolmatt8083 What is your Discord?

**Comment by DerpmanDev** [comment]
> Hi Hi, so the doge links I get from the discord server are being blocked on my school laptop and I was wondering why it is happening, I have never shared my links with anyone nor showed anyone the discord so I am very confused as to why It is happening. I was also wondering if you can deploy the unblocker page inside of a github codespace? If it is possible could I get a tutorial or step by step on how to do so?

Your content keeper is probably detecting them, try making your own links using our DNS method (you can find within our [Discord server](https://discord.gg/unblocking))

**Comment by 1coolmatt8083** [comment]
i dont have a discord account yet

**Comment by 1coolmatt8083** [comment]
oh and yes i think he is making his own

**Comment by 1coolmatt8083** [comment]
thats what i wass helping him with

**Comment by Ny4zU** [comment]
> > Hi Hi, so the doge links I get from the discord server are being blocked on my school laptop and I was wondering why it is happening, I have never shared my links with anyone nor showed anyone the discord so I am very confused as to why It is happening. I was also wondering if you can deploy the unblocker page inside of a github codespace? If it is possible could I get a tutorial or step by step on how to do so?
> 
> Your content keeper is probably detecting them, try making your own links using our DNS method (you can find within our [Discord server](https://discord.gg/unblocking))

Ah yes! The discord! about that... I talked with you last week about this in a ticket about how I got blocked by the bot for thinking I was using a VPN, when I wasn't.

**Comment by astrogames06** [comment]
You can also create your own links by forking the repo and hosting it on vercel.com. Its very simple todo if you need any further help just ask me.

**Comment by Ny4zU** [comment]
Ok so I made my own link, but it's blocked by the school. any way I can get around that?

**Comment by astrogames06** [comment]
> Ok so I made my own link, but it's blocked by the school. any way I can get around that?
> 
> 

Could you send screenshots and explain how you hosted it. Also another website that isn't blocked is astrogames06.github.io

**Comment by astrogames06** [comment]
> Ok so I made my own link, but it's blocked by the school. any way I can get around that?

Could you send screenshots and explain how you did it. Also providing the link would be helpful.

**Comment by DerpmanDev** [comment]
There is no need to provide the link

**Comment by DerpmanDev** [comment]
@Ny4zU If your school has blocked a link, there is nothing we can do about it, that is your school's issue. 

The only way you can get around it is to make more links. A tip when making links is to choose the less popular ones, to prevent getting blocked easily. Additionally, it's also recommended that you don't share the links you make, or they get blocked faster.

@astrogames06 As for how to make the link, please watch this [tutorial](https://www.youtube.com/watch?v=kBTGO672UJ4) to learn how.

If you have any problems regarding a blocked link/content keeper, please do not make a issue here, since we can't do anything about it. If you must ask, then ask the community in our [Discord server.](https://discord.gg/unblocking)

**Comment by gdg-network** [comment]
Derpman = goat
