### ISSUE TITLE
proxy is broken

### ISSUE THREAD

**Issue by PhineasNielsen** [DogeNetwork/v4#73]
iwhen ever i try to searhc something on the proxy it shows this. This network is blocked due to unaddressed abuse complaints about malicious behavior. This page checks to see if it's really a human sending the requests and not a robot coming from this network.

**Comment by DerpmanDev** [comment]
Please do not open issues on our GitHub for problems with our links, you should ask them in our [Discord](https://discord.gg/unblocking) instead.
