### ISSUE TITLE
is not working with ruffle properly

### ISSUE THREAD

**Issue by adnt562378** [DogeNetwork/v4#76]
Every time I try to run a .swf on newgrounds.com, it says that it has failed to load the .wasm file component, causing an error unable to play the .swf file. It says that access to fetch has been blocked by CORS policy. Please fix this in the next patch.

**Comment by KDust7** [comment]
Oh. So what I do to fix this (for newgrounds at least) is I use the dev tools, inspect on the game, then just copy the iframe src url and put that in the proxy. I can elaborate more if you would like if you cannot comprehend.

**Comment by sysolace** [comment]
If the issue still persists, make an issue on **[@titaniumnetwork-dev/Ultraviolet](https://github.com/titaniumnetwork-dev/Ultraviolet/issues/new)**
