### ISSUE TITLE
when i open anything even stuff that isnt blocked on the network (i deployed it with vercel)

### ISSUE THREAD

**Issue by MorroTheCoder** [DogeNetwork/v4#78]
this is the arror the browser gives when goin to anything but the roblox says its working but i dont have roblox to test it
RangeError: Response constructor: Invalid response status code.

**Comment by KDust7** [comment]
So, this problem is a problem with memory, and just means that you’re going to have to use a new link until the memory with your previous link has reset.

**Comment by KDust7** [comment]
Please close the issue if that solves your problem.
