### ISSUE TITLE
Issue with JOY ARK cloud gaming

### ISSUE THREAD

**Issue by porgman102** [DogeNetwork/v4#79]
Doge crashes when link is clicked on this site could be lanschool sneaking in though cannot confirm.

**Comment by DerpmanDev** [comment]
Could you provide more details on your issue? Perhaps a screenshot or a video recording would help

**Comment by porgman102** [comment]
heres a screenshot of the error that appears when I click the joyark link
![Screenshot 2024-06-19 12 15 35 PM](https://github.com/DogeNetwork/v4/assets/142819932/9ecf5f26-b627-4083-997c-fe60033688f8)

**Comment by porgman102** [comment]
if you cant read it is says

 "The webpage at https://pm.stanharvell.com/service/hvtrs8%2F-jmycri.aoo%2F might be temporarily down or it may have moved permanently to a new web address."

**Comment by DerpmanDev** [comment]
That means that the site is not supported with our site. We are integrating another proxy system soon which should hopefully fix that.

**Comment by porgman102** [comment]
> That means that the site is not supported with our site. We are integrating another proxy system soon which should hopefully fix that.

thanks good to see a dev respond to these and nice job on fixing GeoforceNow works like a charm
