### ISSUE TITLE
whats up with this? I cant use reddit or go to any socials

### ISSUE THREAD

**Issue by Brickboxing** [DogeNetwork/v4#80]
![image](https://github.com/DogeNetwork/v4/assets/171631482/40d4719d-b59a-4aac-99ac-9ed34e55a28b)

please tell me theirs another way to get around this

**Comment by DerpmanDev** [comment]
Self-deployed links can have this issue, we recommend creating links using our DNS method or using a link from our Link Bot

Join our Discord [here](https://discord.gg/unblocking) for more info
