### ISSUE TITLE
Um nothing works

### ISSUE THREAD

**Issue by Glam-freddy** [DogeNetwork/v4#82]
hi, so when I use the games and socials it says that it "failed to fetch" isn't found. Does anyone know how to fix this 😅
![Screenshot 2024-06-10 12 47 00 PM](https://github.com/DogeNetwork/v4/assets/172306314/ed0998c5-4297-4241-99dd-f6d1fcdc7e2b)

**Comment by DerpmanDev** [comment]
Are you using a self-deployed link?

**Comment by yet66** [comment]
> hi, so when I use the games and socials it says that it "failed to fetch" isn't found. Does anyone know how to fix this 😅 ![Screenshot 2024-06-10 12 47 00 PM](https://private-user-images.githubusercontent.com/172306314/338323257-ed0998c5-4297-4241-99dd-f6d1fcdc7e2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5ODYzMjEsIm5iZiI6MTcyMDk4NjAyMSwicGF0aCI6Ii8xNzIzMDYzMTQvMzM4MzIzMjU3LWVkMDk5OGM1LTQyOTctNDI0MS05OWRkLWY2ZDFmY2RjN2UyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQxOTQwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTU5MTVlMGMzMzkzYjJjNDA3OWNmNmI5NTA5YTNhZDBkZGI3NDNhNDEyNjVkODA0N2QwNDYzM2E3MzU1MTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-gTOyqKTKBjDqVrAaaAe_5yXTLtFfTd0-j0b9OiQfDU)

clear cache on your browser
