### ISSUE TITLE
blocked

### ISSUE THREAD

**Issue by 2pro12342** [DogeNetwork/v4#83]
its blocked. glitch.com and replit.com still work.

**Comment by 2pro12342** [comment]
And also the link bot doesn't really help all it does is just give me blocked links. but thanks for trying to help.

**Comment by DerpmanDev** [comment]
Do not open issues on the GitHub for blocked links, we really cannot do anything for you

Perhaps you can ask for help in our [Discord](https://discord.gg/unblocking)
