### ISSUE TITLE
I need a favor, can someone create a proxy link for me?

### ISSUE THREAD

**Issue by Brickboxing** [DogeNetwork/v4#93]
I would do it myself (and i have tried) but i cant since i can hardly access anything on the device I'm on and the only way around that is by using proxies of which are hard enough to obtain on their own. it'd also be cool if someone can give me rammerhead proxy links since those in particular are able to give youtube and othersites without an issue or any difficulty. 

please contact me on this site: https://www.librarything.com/profile/leonidas_300

you will need to make an account of which you wont need an email for   

please yall i need this please

**Comment by KDust7** [comment]
Please use the discord when asking for requests, please avoid creating unnecessary issues.

**Comment by DerpmanDev** [comment]
@KDust7 make one for him
