### ISSUE TITLE
Geoforce now isn't working

### ISSUE THREAD

**Issue by porgman102** [DogeNetwork/v4#95]
Geo force is showing a 403 error whenever I sign in on any device it was working a couple weeks ago what happened feel free to respond if you need more info

**Comment by KDust7** [comment]
We are working on getting this fixed, the fix will be released in the next major Doge update.

**Comment by porgman102** [comment]
when will that be roughly just wondering?

**Comment by DerpmanDev** [comment]
GeForce NOW has been fixed
